### PR TITLE
Fix navbar toggle

### PR DESCRIPTION
**Pull request by D1ceWard**
Hello,

This pull request fixes non-working navbar toggle by adding some javascript which toggle `is-active` css class on the burger and the menu when the burger is clicked.

image

The javascript come from the Bulma documentation (see: https://bulma.io/documentation/components/navbar/#navbarJsExample)

### CODE REVIEW

**Comment by D1ceWard** [comment]
Hi, it's been a while, is it good? and could it be merge and release?

**Comment by igorkasyanchuk** [comment]
Hi, oh :)

yes, all is good, thank you for a reminder

Just forgot about it. Will release later today

**Comment by D1ceWard** [comment]
Awesome, thanks ! :1st_place_medal:

**Comment by igorkasyanchuk** [comment]
Successfully registered gem: rails_performance (1.0.2)

Try this version and tell me if everything is OK
Thanks again

**Comment by D1ceWard** [comment]
Everything is OK,  fix works like a charm.
image

**Pull request merged**
