### PR TITLE
Fix initialization and make "enabled" setting work

### PR DESCRIPTION
**Pull request by haffla**
Hey!

I noticed that setting `enabled` to `false` actually doesn't work as expected. The problem is that when the engine code is executed the initializer hasn't even run yet, so `RailsPerformance.enabled` is always `true`.

Fixed it by delaying the middleware configuration using the "rails_performance.middleware" initializer.

Also replaced

- `RailsPerformance.try(:enabled)` with just `RailsPerformance.enabled` (why would the module not respond to `enabled`?)
- `const_defined?` with just `defined?` (I think it's the correct way to check if a gem is installed and has been required)

### CODE REVIEW

**Comment by haffla** [comment]
Hello @igorkasyanchuk 

Did you get a chance to have a look at this?

**Comment by igorkasyanchuk** [comment]
Hi @haffla ,
sorry not enogh time

So as I see https://github.com/igorkasyanchuk/rails_performance/blob/8c7f8a2cdda26992627c830e0db950d88298b27c/app/controllers/rails_performance/rails_performance_controller.rb#L7

this option is just disabling access to the admin panel.

And here: https://github.com/igorkasyanchuk/rails_performance/blob/8917f317e33930c74bbc08180104ee7fa634bb66/lib/rails_performance/engine.rb#L10

Have you created an initializer? Are you saying that this option if set to false in initialized later "true" in the code?

**Comment by haffla** [comment]
I am saying that testing for `enabled` inside of the `Engine` class (`rails_performance/lib/rails_performance/engine.rb`) does not work because when you start your Rails app, the `Engine` is loaded before any of the Rails initializer files like `config/initializers/rails_performance.rb` are loaded. Just test it in your own app and set `enabled` to `false`.

**Comment by igorkasyanchuk** [comment]
Ohh, I see. I thought I've tested and it was working. Good catch on this. Thanks

**Comment by igorkasyanchuk** [comment]
a new version was just released. Thanks for support

**Pull request merged**
