### PR TITLE
Rename README.md to Monitoring fix.md

### PR DESCRIPTION
**Pull request by greatheart2**

### CODE REVIEW

**Comment by igorkasyanchuk** [comment]
And why this is needed?

**Comment by greatheart2** [comment]
Fixed some workflow

**Comment by igorkasyanchuk** [comment]
what workflows?

**Comment by igorkasyanchuk** [comment]
I see that most (if not all) of the gems like https://github.com/heartcombo/devise have the same structure
so don't understand why this is needed

**Comment by igorkasyanchuk** [comment]
image

also you have 2 PR's where you renaming the same file, so looks very strange

**Pull request closed without merging**
